//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_almacen_insumos
    {
        public Nullable<int> id_almacen { get; set; }
        public Nullable<int> id_insumo { get; set; }
        public Nullable<int> id_zona_almacenaje { get; set; }
        public string cantidad { get; set; }
        public string min { get; set; }
        public string max { get; set; }
        public string id_almacen_insumo { get; set; }
    
        public virtual C_almacenes C_almacenes { get; set; }
        public virtual C_insumo_cat C_insumo_cat { get; set; }
        public virtual C_zonas_almacenaje C_zonas_almacenaje { get; set; }
    }
}
