//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_autorizacion_solicitudes
    {
        public int id_autorizacion_solicitud { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_tipo_solicitud { get; set; }
        public Nullable<int> id_motivo_solicitud { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_usuario_autorizador { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public Nullable<int> id_respuesta { get; set; }
    
        public virtual C_autorizacion_motivos C_autorizacion_motivos { get; set; }
        public virtual C_autorizacion_respuestas C_autorizacion_respuestas { get; set; }
        public virtual C_autorizaciones_tipos C_autorizaciones_tipos { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
