//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bo_semanas_trans_rp
    {
        public int id_bo_semanas_calculo_rp { get; set; }
        public Nullable<int> id_producto_clasificacion { get; set; }
        public string sku_insumo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> valor_rango_proteccion_1 { get; set; }
        public Nullable<decimal> valor_rango_proteccion_2 { get; set; }
    }
}
