//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bo_suc_ir
    {
        public string id_bo_suc_ir { get; set; }
        public string id_sucursal { get; set; }
        public Nullable<int> id_invreal { get; set; }
        public Nullable<int> id_bo_g { get; set; }
        public string fecha { get; set; }
    
        public virtual C_bo_g C_bo_g { get; set; }
        public virtual C_suc_invreal C_suc_invreal { get; set; }
    }
}
