//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bo_orden_complemento
    {
        public string id_bo_almacen { get; set; }
        public string id_insumo { get; set; }
        public string cantidad { get; set; }
        public string status { get; set; }
        public string nota { get; set; }
        public string id_bo_orden_complemento { get; set; }
    }
}
