//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bo_porc_df
    {
        public int id_bo_porc_df { get; set; }
        public Nullable<int> id_bo_df_ap { get; set; }
        public Nullable<int> id_insumo { get; set; }
        public string porc_proteccion { get; set; }
        public string fecha { get; set; }
    
        public virtual C_bo_diafestivo_ap C_bo_diafestivo_ap { get; set; }
    }
}
