//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bo_semanas_trans_par
    {
        public int id_bo_semanas_trans_p { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string codigo_empresa { get; set; }
        public string codigo_sucursal { get; set; }
        public string id_bo_anos_param { get; set; }
        public string id_bo_festivos_param { get; set; }
        public Nullable<bool> calculo_ultimo_mes { get; set; }
        public Nullable<bool> calculo_ultimos_7_dias { get; set; }
        public Nullable<int> no_dias_entrega { get; set; }
        public Nullable<int> dias_entrega { get; set; }
        public Nullable<decimal> porc_proteccion_ch { get; set; }
        public Nullable<decimal> porc_proteccion_me { get; set; }
        public Nullable<decimal> porc_proteccion_gd { get; set; }
        public Nullable<bool> estatus { get; set; }
    }
}
