//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bo_calculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_bo_calculo()
        {
            this.C_bo_calculo_pe = new HashSet<C_bo_calculo_pe>();
        }
    
        public int id_bo_calculo { get; set; }
        public Nullable<int> id_bo_g { get; set; }
        public string id_sucursal { get; set; }
        public string id_categoria { get; set; }
        public string id_insumo { get; set; }
        public string cant_emp { get; set; }
        public string cant_suelto { get; set; }
        public string cant_emp_pe { get; set; }
        public string cant_suelto_pe { get; set; }
        public string porc_proteccion { get; set; }
        public string fecha_calculo { get; set; }
    
        public virtual C_bo_g C_bo_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bo_calculo_pe> C_bo_calculo_pe { get; set; }
    }
}
