//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bo_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_bo_g()
        {
            this.C_bo_calculo = new HashSet<C_bo_calculo>();
            this.C_bo_diafestivo_ap = new HashSet<C_bo_diafestivo_ap>();
            this.C_bo_suc_ir = new HashSet<C_bo_suc_ir>();
        }
    
        public int id_bo_g { get; set; }
        public string fecha { get; set; }
        public Nullable<System.DateTime> tendencia1 { get; set; }
        public Nullable<System.DateTime> tendencia2 { get; set; }
        public Nullable<System.DateTime> venta1 { get; set; }
        public Nullable<System.DateTime> venta2 { get; set; }
        public string dia_ruta { get; set; }
        public Nullable<System.DateTime> fecha_ruta { get; set; }
        public Nullable<System.DateTime> dias_cubierto1 { get; set; }
        public Nullable<System.DateTime> dias_cubiertofin { get; set; }
        public Nullable<int> no_dias_cubiertos { get; set; }
        public Nullable<bool> status_captura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bo_calculo> C_bo_calculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bo_diafestivo_ap> C_bo_diafestivo_ap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bo_suc_ir> C_bo_suc_ir { get; set; }
    }
}
