//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_campaña_codigos
    {
        public Nullable<int> id_campaña { get; set; }
        public string codigo { get; set; }
        public string status { get; set; }
        public Nullable<int> id_sucursal_canje { get; set; }
        public Nullable<int> id_usuario_canje { get; set; }
        public Nullable<System.DateTime> fecha_canje { get; set; }
        public Nullable<int> id_cliente_canje { get; set; }
        public string id_campaña_codigo { get; set; }
    
        public virtual C_campañas C_campañas { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
    }
}
