//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_cajas_tipo_mov
    {
        public int id_cajas_tipo_mov { get; set; }
        public string concepto_mov { get; set; }
        public Nullable<bool> entrada_salida { get; set; }
    }
}
