//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_cajas_movimientos
    {
        public int id_cajas_movimiento { get; set; }
        public Nullable<int> id_caja { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_mov { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> id_cajas_tipo_mov { get; set; }
        public Nullable<bool> entrada_salida { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual C_cajas_g C_cajas_g { get; set; }
    }
}
