//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_orden_articulos
    {
        public int id_compras_articulos { get; set; }
        public Nullable<int> id_compra_orden { get; set; }
        public string sku { get; set; }
        public string sku_insumo { get; set; }
        public string cantidad { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> importe_subtotal { get; set; }
        public Nullable<decimal> importe_iva { get; set; }
        public Nullable<decimal> imorte_total { get; set; }
    }
}
