//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_orden
    {
        public int id_compra_orden { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<System.DateTime> fecha_orden { get; set; }
        public Nullable<System.DateTime> fecha_limite_requerida { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_destino { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string importe_letra { get; set; }
        public Nullable<int> id_leyendas_condiciones { get; set; }
        public Nullable<int> id_firmantes { get; set; }
        public Nullable<int> estatus_orden { get; set; }
        public Nullable<bool> generar_oc { get; set; }
    }
}
