//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_colonias
    {
        public int id_colonia { get; set; }
        public Nullable<int> cve_colonia { get; set; }
        public string colonia { get; set; }
        public Nullable<int> id_codigo_postal { get; set; }
        public Nullable<int> d_codigo { get; set; }
        public Nullable<int> id_asenta_cpcons { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> usuario_alta { get; set; }
        public Nullable<decimal> costo_envio { get; set; }
    
        public virtual C_codigos_postales C_codigos_postales { get; set; }
    }
}
