//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_empleados_team_card
    {
        public int id_empleado_team_card { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public string no_tarjeta { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<decimal> monto_autorizado { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> limite { get; set; }
        public string NIP { get; set; }
        public Nullable<System.DateTime> valida_desde { get; set; }
        public Nullable<System.DateTime> valida_hasta { get; set; }
        public string notas { get; set; }
        public Nullable<bool> activa { get; set; }
    
        public virtual C_empleados C_empleados { get; set; }
    }
}
