//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_empleados
    {
        public string nombres { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public string no_interior { get; set; }
        public string no_exterior { get; set; }
        public Nullable<int> ciudad { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> municipio { get; set; }
        public Nullable<int> cp { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string nss { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<int> puesto { get; set; }
        public string curp { get; set; }
        public string telefono_celular { get; set; }
        public string telefono_casa { get; set; }
        public string telefono_contacto { get; set; }
        public Nullable<int> tipo_sangre { get; set; }
        public string id_empleado { get; set; }
    }
}
