//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_equipo_sucursal
    {
        public string codigo_sucursal { get; set; }
        public string nombre_equipo { get; set; }
        public string id_tipo_equipo { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public string nss { get; set; }
        public string mac_address { get; set; }
        public string ip_address { get; set; }
        public Nullable<bool> activo { get; set; }
        public int id_equipo_sucursal { get; set; }
    
        public virtual C_sucursales C_sucursales { get; set; }
    }
}
