//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_facturas
    {
        public string id_factura { get; set; }
        public string folio { get; set; }
        public string fecha { get; set; }
        public int id_CFDI_informacion { get; set; }
    
        public virtual C_cfdi_informacion C_cfdi_informacion { get; set; }
    }
}
