//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_grupo_productos_prods
    {
        public int id_grupo_productos_prods { get; set; }
        public Nullable<int> id_grupo_productos_det { get; set; }
        public string sku_producto { get; set; }
        public string descripcion { get; set; }
    
        public virtual C_grupo_productos_d C_grupo_productos_d { get; set; }
        public virtual C_grupo_productos_d C_grupo_productos_d1 { get; set; }
        public virtual C_grupo_productos_d C_grupo_productos_d2 { get; set; }
    }
}
