//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_grupo_productos_codigos
    {
        public int id_grupo_productos_codigo { get; set; }
        public Nullable<int> id_grupo_productos { get; set; }
        public string codigo_grupo { get; set; }
        public Nullable<int> no_codigos_autorizados { get; set; }
        public Nullable<System.DateTime> vigente_desde { get; set; }
        public Nullable<System.DateTime> vigente_hasta { get; set; }
        public Nullable<int> id_destino_social { get; set; }
        public Nullable<int> saldo { get; set; }
        public string descripcion { get; set; }
        public string reglas { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
