//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_grupo_productos_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_grupo_productos_g()
        {
            this.C_campañas = new HashSet<C_campañas>();
            this.C_grupo_productos_codigos = new HashSet<C_grupo_productos_codigos>();
            this.C_grupo_productos_d = new HashSet<C_grupo_productos_d>();
            this.C_grupo_productos_sucursales = new HashSet<C_grupo_productos_sucursales>();
        }
    
        public int id_grupo_productos { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_grupo_producto_tipo { get; set; }
        public Nullable<int> id_grupo_producto_subclase { get; set; }
        public Nullable<int> id_grupo_aplica_operacion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_final { get; set; }
        public string restricciones { get; set; }
        public Nullable<bool> status { get; set; }
        public string banner_pantalla { get; set; }
        public string banner_pos { get; set; }
        public Nullable<bool> mayor_precio { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> precio_unico { get; set; }
        public Nullable<bool> requiere_codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_campañas> C_campañas { get; set; }
        public virtual C_grupo_aplica_operacion C_grupo_aplica_operacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_grupo_productos_codigos> C_grupo_productos_codigos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_grupo_productos_d> C_grupo_productos_d { get; set; }
        public virtual C_grupo_productos_subclases C_grupo_productos_subclases { get; set; }
        public virtual C_grupo_productos_tipos C_grupo_productos_tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_grupo_productos_sucursales> C_grupo_productos_sucursales { get; set; }
    }
}
