//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_grupo_productos_codigos_movs
    {
        public int id_grupo_productos_codigos_aut { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public string codigo_prupo { get; set; }
        public Nullable<System.DateTime> fecha_aplicacion { get; set; }
        public string notas { get; set; }
    }
}
