//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_sucursal
    {
        public int id_insumo_sucursal { get; set; }
        public Nullable<int> id_insumo { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string C__proteccion { get; set; }
        public string min { get; set; }
        public string max { get; set; }
        public int id_zona_almacenaje { get; set; }
    
        public virtual C_insumo_cat C_insumo_cat { get; set; }
        public virtual C_zona_almacen_suc C_zona_almacen_suc { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
    }
}
