//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_cat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_insumo_cat()
        {
            this.C_insumo_sucursal = new HashSet<C_insumo_sucursal>();
        }
    
        public int id_insumo { get; set; }
        public string insumo { get; set; }
        public string id_categoria { get; set; }
        public string id_tipo { get; set; }
        public string nivel_insumo { get; set; }
        public string caducidad { get; set; }
        public Nullable<int> Id_tipo_empaque { get; set; }
        public string presentacion_cantidad { get; set; }
        public Nullable<int> id_unidad { get; set; }
        public string porc_proteccion { get; set; }
        public string costo_real { get; set; }
        public string costo_directo { get; set; }
    
        public virtual C_tipo_empaque C_tipo_empaque { get; set; }
        public virtual C_unidades C_unidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_sucursal> C_insumo_sucursal { get; set; }
    }
}
