//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_cat_old
    {
        public int id_insumo { get; set; }
        public string sku_insumo { get; set; }
        public string codigo_barra_std { get; set; }
        public string nombre_insumo { get; set; }
        public Nullable<int> id_insumo_clasif { get; set; }
        public Nullable<int> id_tipo_inventario { get; set; }
        public Nullable<decimal> nivel_reorden_insumo { get; set; }
        public Nullable<decimal> dias_caducidad { get; set; }
        public Nullable<int> Id_tipo_empaque { get; set; }
        public Nullable<int> Id_tipo_envase { get; set; }
        public Nullable<decimal> presentacion_cantidad { get; set; }
        public Nullable<int> id_unidad { get; set; }
        public Nullable<decimal> porc_proteccion { get; set; }
        public Nullable<decimal> costo_real { get; set; }
        public Nullable<decimal> costo_directo { get; set; }
        public Nullable<int> inventario_corte { get; set; }
        public Nullable<int> inventario_general { get; set; }
        public Nullable<int> bo_incluir { get; set; }
        public Nullable<decimal> bo_redondeo { get; set; }
        public Nullable<int> bo_provdirecto { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_tipo_empaque C_tipo_empaque { get; set; }
        public virtual C_unidades C_unidades { get; set; }
    }
}
