//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_cat
    {
        public int C_id_insumo { get; set; }
        public string C______sku_insumo { get; set; }
        public string codigo_barra_std { get; set; }
        public string nombre_insumo { get; set; }
        public Nullable<int> C______id_insumo_clasif { get; set; }
        public Nullable<int> C______id_tipo_inventario { get; set; }
        public Nullable<double> C______nivel_reorden_insumo { get; set; }
        public Nullable<int> C______dias_caducidad { get; set; }
        public Nullable<int> C______Id_tipo_empaque { get; set; }
        public Nullable<int> C______Id_tipo_envase { get; set; }
        public string C______presentacion_cantidad { get; set; }
        public Nullable<int> C______id_unidad { get; set; }
        public Nullable<decimal> C______porc_proteccion { get; set; }
        public Nullable<decimal> C______costo_real { get; set; }
        public Nullable<decimal> C______costo_directo { get; set; }
        public Nullable<bool> inventario_corte { get; set; }
        public Nullable<bool> inventario_general { get; set; }
        public Nullable<bool> bo_incluir { get; set; }
        public string bo_redondeo { get; set; }
        public Nullable<int> bo_provdirecto { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<bool> C______activo { get; set; }
    }
}
