//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_insumo_sucursal
    {
        public int id_insumo_sucursal { get; set; }
        public string sku_insumo { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> porc_proteccion { get; set; }
        public Nullable<decimal> min { get; set; }
        public Nullable<decimal> max { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_movimiento { get; set; }
        public int id_zona_almacenaje { get; set; }
    
        public virtual C_insumo_cat C_insumo_cat { get; set; }
        public virtual C_sucursales C_sucursales { get; set; }
    }
}
