//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_marcas_datos_fiscales
    {
        public int id_marcas_datos_fiscales { get; set; }
        public Nullable<int> id_marca { get; set; }
        public string nombre { get; set; }
        public string razon_Social { get; set; }
        public string rfc { get; set; }
        public string notas { get; set; }
    }
}
