//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_modulos_sub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_modulos_sub()
        {
            this.C_modulos_sub_permisos = new HashSet<C_modulos_sub_permisos>();
        }
    
        public int id_modulos_sub { get; set; }
        public Nullable<int> id_modulo { get; set; }
        public string nombre { get; set; }
        public string icono { get; set; }
        public string funcion { get; set; }
        public string controlador { get; set; }
        public string parametros { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_modulos C_modulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_modulos_sub_permisos> C_modulos_sub_permisos { get; set; }
    }
}
