//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_notificaciones_mensajes
    {
        public int id_notificacion { get; set; }
        public string codigo_usuario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public Nullable<int> id_tipo_notificacion { get; set; }
        public Nullable<int> id_subtipo_notificacion { get; set; }
        public string mensaje_notificacion { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
