//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_parametros_empresa
    {
        public int id_parametro_empresa { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string id_parametro { get; set; }
        public Nullable<decimal> valor_numerico { get; set; }
        public string valor_string { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_empresas C_empresas { get; set; }
    }
}
