//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_parametros_sucursales
    {
        public int id_parametro_sucursal { get; set; }
        public Nullable<int> id_parametro { get; set; }
        public Nullable<int> id_sucursal { get; set; }
    
        public virtual C_parametros C_parametros { get; set; }
    }
}
