//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_pedidos_empleados
    {
        public int id_pedido_empleado { get; set; }
        public int id_pedido { get; set; }
        public int id_empleado { get; set; }
        public bool status { get; set; }
    
        public virtual C_empleados C_empleados { get; set; }
        public virtual C_pedidos C_pedidos { get; set; }
    }
}
