//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_pedidos_d
    {
        public int id_pedido_d { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_producto { get; set; }
        public string cantidad { get; set; }
        public string pedido_d_status { get; set; }
    
        public virtual C_pedidos C_pedidos { get; set; }
    }
}
