//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_pos_caja_movs
    {
        public long id_caja_movs { get; set; }
        public string fecha { get; set; }
        public string hora { get; set; }
        public string usuario { get; set; }
        public string tipo { get; set; }
        public string naturaleza { get; set; }
        public string monto { get; set; }
        public string observacion { get; set; }
        public string terminal { get; set; }
    }
}
