//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_producto_tipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_producto_tipo()
        {
            this.C_producto_clasificacion = new HashSet<C_producto_clasificacion>();
        }
    
        public int id_producto_tipo { get; set; }
        public string nombre { get; set; }
        public string alias_sku { get; set; }
        public string icono_web { get; set; }
        public string icono_mobil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_producto_clasificacion> C_producto_clasificacion { get; set; }
    }
}
