//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_producto_clasificacion
    {
        public int id_producto_clasificacion { get; set; }
        public Nullable<int> id_tipo_producto { get; set; }
        public string nombre_producto_clasificacion { get; set; }
    }
}
