//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_presentaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_presentaciones()
        {
            this.C_producto_presentacion = new HashSet<C_producto_presentacion>();
        }
    
        public int id_presentacion { get; set; }
        public string nivel { get; set; }
        public string presentacion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<int> id_unidad { get; set; }
    
        public virtual C_unidades_medida C_unidades_medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_producto_presentacion> C_producto_presentacion { get; set; }
    }
}
