//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_proveedores
    {
        public int id_proveedor { get; set; }
        public string cve_proveedor { get; set; }
        public string nombre_proveedor { get; set; }
        public Nullable<int> id_tipo_servicio { get; set; }
        public string razon_social { get; set; }
        public string domicilio { get; set; }
        public string telefono_1 { get; set; }
        public string telefono_2 { get; set; }
        public string rfc { get; set; }
    }
}
