//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_promociones_prods
    {
        public int id_promocion_prods { get; set; }
        public Nullable<int> id_promocion_det { get; set; }
        public string id_producto { get; set; }
        public string desc { get; set; }
    
        public virtual C_promociones_d C_promociones_d { get; set; }
    }
}
