//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_recetas
    {
        public int id_receta { get; set; }
        public string sku { get; set; }
        public string sku_insumo { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> costo_total { get; set; }
        public Nullable<double> costo_porcion { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
