//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sociedades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_sociedades()
        {
            this.C_marcas_sociedades = new HashSet<C_marcas_sociedades>();
            this.C_sociedades_empresas = new HashSet<C_sociedades_empresas>();
        }
    
        public int id_sociedad { get; set; }
        public string nombre_sociedad { get; set; }
        public string razon_social { get; set; }
        public string rfc { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string representante { get; set; }
        public string correo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_marcas_sociedades> C_marcas_sociedades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sociedades_empresas> C_sociedades_empresas { get; set; }
    }
}
