//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sociedades_empresas
    {
        public int id_sociedad_empresa { get; set; }
        public Nullable<int> id_sociedad { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> fecha_registro { get; set; }
    
        public virtual C_sociedades C_sociedades { get; set; }
    }
}
