//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_suc_invreal_d
    {
        public string id_suc_invreal_d { get; set; }
        public Nullable<int> id_suc_invreal { get; set; }
        public string id_insumo { get; set; }
        public string cantidad { get; set; }
        public Nullable<int> comentarios { get; set; }
    
        public virtual C_suc_invreal C_suc_invreal { get; set; }
    }
}
