//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_suc_invreal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_suc_invreal()
        {
            this.C_bo_suc_ir = new HashSet<C_bo_suc_ir>();
            this.C_suc_invreal_d = new HashSet<C_suc_invreal_d>();
        }
    
        public int id_suc_invreal { get; set; }
        public string id_sucursal { get; set; }
        public string id_usuario { get; set; }
        public string fecha { get; set; }
        public string status_captura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bo_suc_ir> C_bo_suc_ir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_suc_invreal_d> C_suc_invreal_d { get; set; }
    }
}
