//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sval_deposito_envases
    {
        public int id_sval_envases { get; set; }
        public Nullable<int> id_sval_deposito { get; set; }
        public string no_sello_plomo { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
