//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sval_recepcion
    {
        public int id_recepcion_valores { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<int> id_terminal_captura { get; set; }
        public Nullable<int> id_usuario_captura { get; set; }
        public Nullable<int> id_usuario_cajero { get; set; }
        public string nip_cajero { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_sval_orden { get; set; }
        public Nullable<decimal> importe_contenido_efectivo { get; set; }
        public Nullable<decimal> importe_contenido_documentos { get; set; }
        public Nullable<decimal> total_importe_contenido { get; set; }
        public Nullable<int> id_desglose_billetes { get; set; }
        public Nullable<int> id_desglose_monedas { get; set; }
    }
}
