//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sval_orden_monedas
    {
        public int id_sval_orden_monedas { get; set; }
        public Nullable<int> id_sval_orden { get; set; }
        public Nullable<int> id_sval_desglose_monedas { get; set; }
        public Nullable<decimal> no_piezas { get; set; }
        public Nullable<System.DateTime> fecha_captura { get; set; }
    }
}
