//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sval_arqueos
    {
        public int id_sval_arqueo { get; set; }
        public Nullable<System.DateTime> fecha_arqueo { get; set; }
        public Nullable<decimal> saldo_anterior { get; set; }
        public Nullable<decimal> entradas_sucursal { get; set; }
        public Nullable<decimal> salidas_nominas { get; set; }
        public Nullable<decimal> salidas_bancos { get; set; }
        public Nullable<decimal> bill_abanico { get; set; }
        public Nullable<decimal> bill_en_transito { get; set; }
        public Nullable<decimal> bill_falso_leyenda { get; set; }
        public Nullable<decimal> bill_picos { get; set; }
        public Nullable<decimal> mon_flotantes { get; set; }
        public Nullable<decimal> mon_fracciones { get; set; }
        public Nullable<decimal> total_fisico_boveda { get; set; }
        public Nullable<decimal> total_proceso { get; set; }
        public Nullable<decimal> faltante { get; set; }
        public Nullable<decimal> sobrante { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_supervisor { get; set; }
        public Nullable<int> id_gerente { get; set; }
    }
}
