//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_team_card_movs
    {
        public int id_team_card_movs { get; set; }
        public Nullable<int> id_empelado { get; set; }
        public Nullable<int> id_team_card_tipo_mov { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<bool> estatus { get; set; }
    }
}
