//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tipo_empaque
    {
        public int id_tipo_empaque { get; set; }
        public string nombre { get; set; }
        public string largo { get; set; }
        public string ancho { get; set; }
        public string alto { get; set; }
    }
}
