//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tracking_status_log
    {
        public int id_tracking_status_log { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_tracking_status1 { get; set; }
        public Nullable<int> id_tracking_status2 { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> seg_recorridos { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_pedidos C_pedidos { get; set; }
        public virtual C_tracking_status C_tracking_status { get; set; }
        public virtual C_tracking_status C_tracking_status1 { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
