//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_usuarios_sucursales
    {
        public int id_usuarios_sucursales { get; set; }
        public string codigo_sucursal { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
        public Nullable<bool> prestamo { get; set; }
        public string codigo_sucursal_prestamo { get; set; }
    
        public virtual C_sucursales C_sucursales { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }

        public virtual CS_usuarios CS_usuarios { get; set; }
    }
}
