//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_zona_almacen_suc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_zona_almacen_suc()
        {
            this.C_insumo_sucursal = new HashSet<C_insumo_sucursal>();
        }
    
        public int id_zona_almacen_suc { get; set; }
        public string nombre { get; set; }
        public string descripcio { get; set; }
        public string ancho { get; set; }
        public string largo { get; set; }
        public string alto { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_insumo_sucursal> C_insumo_sucursal { get; set; }
    }
}
