//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_callcenter_cliente
    {
        public int ID_CLIENTE { get; set; }
        public string TELEFONO { get; set; }
        public string NOMBRE { get; set; }
        public string CALLE { get; set; }
        public string ESPECIFICACION { get; set; }
        public string COLONIA_ID { get; set; }
        public string REFERENCIA { get; set; }
        public string ADICIONALES { get; set; }
        public string APP_UBICACION { get; set; }
        public string APP_PWD { get; set; }
        public string APP_GCM { get; set; }
        public string ULTIMA_COMPRA { get; set; }
    }
}
