//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_permisos_asignados
    {
        public string ID_USUARIO { get; set; }
        public string ID_ROL { get; set; }
        public string ID_PERMISO { get; set; }
        public string ID_MODULO { get; set; }
        public string STATUS { get; set; }
        public decimal ID_PERMISO_ASIGNADOS { get; set; }
    
        public virtual CS_modulos CS_modulos { get; set; }
        public virtual CS_permisos CS_permisos { get; set; }
        public virtual CS_roles CS_roles { get; set; }
        public virtual CS_usuarios CS_usuarios { get; set; }
    }
}
