//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_usuarios()
        {
            this.C_usuarios_sucursales = new HashSet<C_usuarios_sucursales>();
            this.CS_permisos_asignados = new HashSet<CS_permisos_asignados>();
        }
    
        public int ID_USUARIO { get; set; }
        public string CODIGO_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string PASS { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public string ESTADO_ACTUAL { get; set; }
        public Nullable<int> ID_SERVICIO { get; set; }
        public Nullable<int> NIVEL_USUARIO { get; set; }
        public string PASS_VAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_sucursales> C_usuarios_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_permisos_asignados> CS_permisos_asignados { get; set; }
        public virtual CS_roles CS_roles { get; set; }

        public virtual C_servicios C_Servicios { get; set; }
    }
}
