//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_callcenter_clientes_adicionales
    {
        public long id { get; set; }
        public string telefono { get; set; }
        public string calle { get; set; }
        public string especificacion { get; set; }
        public string colonia_id { get; set; }
        public string referencia { get; set; }
        public string app_ubicacion { get; set; }
        public string default_app { get; set; }
    }
}
