//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_encuesta_1
    {
        public int id_usuario_encuesta { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string Pregunta_1 { get; set; }
        public string Respuesta_1 { get; set; }
        public string Pregunta_2 { get; set; }
        public string Respuesta_2 { get; set; }
        public string Pregunta_3 { get; set; }
        public string Respuesta_3 { get; set; }
        public Nullable<int> Pregunta_4 { get; set; }
        public Nullable<bool> Contestada { get; set; }
    }
}
