//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Usuarios
    {
        public long id_usuario { get; set; }
        public string nombre { get; set; }
        public string @ref { get; set; }
        public string pass { get; set; }
        public string nivel { get; set; }
        public string tarjeta_empleado { get; set; }
        public string tarjeta_empleado_limite { get; set; }
        public string tarjeta_empleado_disponible { get; set; }
        public string app_user_id { get; set; }
        public string app_android_user_id_reg { get; set; }
        public string app_sucursal_id_asignado { get; set; }
        public string app_user_id_ultima_coordenada { get; set; }
        public string app_user_id_ultima_actualizacion { get; set; }
        public string app_user_ensucursal { get; set; }
        public string gafete_identificacion { get; set; }
        public string estado_actual { get; set; }
        public string empresas { get; set; }
        public string estado_usuario { get; set; }
    }
}
