//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.PERMISOS_ASIGNADOS = new HashSet<PERMISOS_ASIGNADOS>();
            this.USUARIO_LOGIN = new HashSet<USUARIO_LOGIN>();
        }
    
        public string ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string REF { get; set; }
        public string PASS { get; set; }
        public string ID_PERFIL { get; set; }
        public string TARJETA_EMPLEADO { get; set; }
        public string ESTADO_ACTUAL { get; set; }
        public string GAFETE_IDENTIFICACION { get; set; }
        public string ID_ROL { get; set; }
    
        public virtual PERFILES PERFILES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISOS_ASIGNADOS> PERMISOS_ASIGNADOS { get; set; }
        public virtual ROLES ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_LOGIN> USUARIO_LOGIN { get; set; }
    }
}
