//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_empresas_sucursales
    {
        public string codigo_sucursal { get; set; }
        public string codigo_sucursal1 { get; set; }
        public string codigo_empresa { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nombre { get; set; }
    }
}
